/* prettier-ignore-start */
/* eslint-disable */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router's Vite plugin.
// Do not edit this file manually — it will be overwritten on next `dev` or `build`.

// ──────────────────────────────────────────────────────────────────────────────
// STUB — the real file is generated at build/dev time by @tanstack/router-vite-plugin
// ──────────────────────────────────────────────────────────────────────────────

import { RootRoute } from "./routes/__root";
import { Route as IndexRoute } from "./routes/index";
import { Route as AuthRoute } from "./routes/auth";
import { Route as MoversRoute } from "./routes/movers";
import { Route as PortfolioRoute } from "./routes/portfolio";
import { Route as ChatRoute } from "./routes/chat";

export { RootRoute, IndexRoute, AuthRoute, MoversRoute, PortfolioRoute, ChatRoute };

export const routeTree = RootRoute.addChildren([
  IndexRoute,
  AuthRoute,
  MoversRoute,
  PortfolioRoute,
  ChatRoute,
]);
/* prettier-ignore-end */
